#dev环境配置
server:
   port: 8081

spring:
  datasource:
    url: jdbc\:postgresql\://192.168.50.53\:5432/db_ztfx?&language\=us_english&charset\=utf8&ApplicationName\=ztfx
    username: gpadmin
    password: gpadmin
    driver-class-name: org.postgresql.Driver

