#dev环境配置
server:
   port: 8081

spring:
  datasource:
    url: jdbc:postgresql://47.94.90.184:5432/db_data_quality?&language=us_english&charset=utf8&ApplicationName=quality
    username: gpadmin
    password: gpadmin
    driver-class-name: org.postgresql.Driver

